### PR TITLE
Add search bar

### LINKED ISSUE #2: add search bar
a search bar at the top  
- with rounded edges
- should not have full width
- should have a search icon

### PR DESCRIPTION
**Pull request by Robertw8**
This PR resolves #2 by creating a SearchBar.jsx and styling it in search-bar.css. Also, added "search" icon as was required in the issue. If search bar needs any improvements like styling or functionality, please detail requirements and I'm gonna do it.

### CODE REVIEW

**Comment by nveshaan** [comment]
image
could u do something like this  
only difference is the search icon is in the place of hamburger menu (three lines on the right)
@Robertw8

**Comment by nveshaan** [comment]
also a small suggestion, configure your formatted (prettier - most used) to use 2 spaces for a tab (you're using 8)
this is totally your choice, but a lot of open repos follow this standard

**Comment by Robertw8** [comment]
Alright

**Comment by nveshaan** [comment]
tyvm, it looks very good
if u could make the search icon clickable, it would be very nice
some suggested changes,
- a bit more spacing between todo heading and search bar
- a longer width

**Comment by Robertw8** [comment]
What you mean by "clickable" icon? Because now when you click on that icon it makes focus on input

**Comment by nveshaan** [comment]
wrap the input tag with a form tag, and make the icon a button which submits the form
the form sends the search input to the backend and retrieves the matches todos, I will do the backend part myself
you only have to work on the front end, (u can add the backend route as well if u wish to)
tyvm

**Comment by nveshaan** [comment]
you can make the search icon a button by wrapping the SVG tag with a button tag

**Comment by nveshaan** [comment]
lgtm!! tyvm!!

**Pull request merged**
